repos:
  # 1. General Hygiene: Basic file checks
  - repo: https://github.com
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # 2. Formatting: Prettier (Supports TS, JS, HTML, CSS)
  - repo: https://github.com
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:[ts, js, html, css]

  - repo: https://github.com
    rev: v9.0.6
    hooks:
      - id: shellcheck
      
  - repo: https://github.com
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
